# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-04 20:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tea', '0003_auto_20171004_1352'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tea',
            old_name='gal_img',
            new_name='gallery_image',
        ),
        migrations.RenameField(
            model_name='tea',
            old_name='m_image',
            new_name='main_image',
        ),
    ]
