# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-04 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tea', '0004_auto_20171004_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='tea',
            name='brewing_method',
            field=models.ManyToManyField(help_text='Select the brewing methods.', to='tea.BrewingMethod'),
        ),
    ]
