# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-04 22:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tea', '0005_tea_brewing_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='tea',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tea',
            name='name',
            field=models.CharField(help_text='Enter the name of the tea.', max_length=200),
        ),
    ]
