# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-07 03:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tea', '0006_auto_20171004_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='tea',
            name='image_name1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='tea',
            name='main_image',
            field=models.ImageField(blank=True, default='', upload_to='imgs'),
        ),
    ]
