# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-07 04:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tea', '0008_tea_image_name2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tea',
            name='gallery_image',
        ),
        migrations.RemoveField(
            model_name='tea',
            name='main_image',
        ),
    ]
